### ISSUE TITLE
Web component

### ISSUE THREAD

**Issue by cihad** [TalhaK15/dropdown-menu#11]
Hazirladigimiz kutuphane istenirse Web Component olarak kullanilabilsin. Bu kodlar baska bir dosyada tutulsun.

**Comment by talhabw** [comment]
Web component için yeni bir [branch](https://github.com/TalhaK15/dropdown-menu/blob/web-component) oluşturdum. Elementin sayfada gözükmesi ve özelleştirme konusunda bir sıkıntı yaşamıyorum.

Ama web component içerisindeki butonu js üzerinden seçemiyorum. Butona id olarak 15 veriyorum. Tüm butonları seçip, component içerisinde olan butonun id'sine baktığımda da 15'i görebiliyorum. ([bknz](https://github.com/TalhaK15/dropdown-menu/blob/web-component/demo/index.js#L3,L5))

Ama

`document.querySelector("#15")`

şeklinde seçmeye çalıştığımda

`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#15' is not a valid selector.`

hatası alıyorum. Sebebini anlayamadım.
