### ISSUE TITLE
Demo sayfasi mobil uyumlu olsun.

### ISSUE THREAD

**Issue by cihad** [TalhaK15/dropdown-menu#12]

**Comment by cihad** [comment]
Mobilde bir karisiklik var. Yukarida cikmasi gereken menu asagida cikiyor. Asagida cikmasi gereken yukarida...

**Comment by talhabw** [comment]
duzeltmeye calistim. ([commit](https://github.com/TalhaK15/dropdown-menu/commit/10f035779fb921be01e9ac53393cf3c30711e175)) her seferinde o anki viewporta gore kontrol etmesini istiyorum. ama kod her buton icin sadece 1 kere hesapliyor sonra ekran degisse de hala menuyu aynı tarafta cikarmaya devam ediyor. 

bu sorunu cozemedim.
