### ISSUE TITLE
animasyonlu olarak menu acilmasi

### ISSUE THREAD

**Issue by cihad** [TalhaK15/dropdown-menu#7]
dropdown.css ile kutuphanemiz ile alakali css'leri bu dosyaya koyalim. Sonra burda bazi css siniflari tanimlayalim. Ornegin menu elemanina `fade`, `bubble` gibi sinif verildigi zaman bu efektler ile acilacak sekilde kodumuzu gelistirelim.

**Comment by cihad** [comment]
https://jsfiddle.net/8xz4n0f3/ burda bir tane ornek yaptim css ile. Ama sen bunu gelistirmelisin. Bu yeterli bir ornek degil. Sadece fikir edinmen acisindan...

**Comment by talhabw** [comment]
yapabildigim kadariyla bir animasyon ekledim. ileride cesitlendirebilirim.
